from schemas import Human, Mammals, Cat, Dog, Student


mammals = Mammals('python', 3, 'male')
mammals.hello_iam_mammals()
human = Human('Human', 15, 'male', "Сергей")
human.hello_iam_mammals()
human.say_hello()
cat = Cat('Cat', 15, 'male', 'Kot9')
dog = Dog('Dog', 12, 'male', 'Tobik')
dog.make_sound()
cat.make_sound()
cat.info()
dog.info()
cat.hello_iam_mammals()
dog.hello_iam_mammals()
student1 = Student('Human', 19, 'male', 'Andrey', 5)
student2 = Student('Human', 19, 'female', 'Kristina', 4)
print(student1 == student2)
print(student1 > student2)
print(student1 < student2)
print(student1 >= student2)
print(student1 <= student2)